language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script: npm test
deploy:
  provider: heroku
  api_key: $heroku_api_key
  app: hapi-react-spa
  run:
    - "yarn install"
    - "npm run build"